# https://artifacthub.io/packages/helm/seaweedfs-operator/seaweedfs-operator
# https://github.com/seaweedfs/seaweedfs-operator

namespace: seaweedfs-operator
resources:
  - namespace.yaml
helmCharts:
  - name: seaweedfs-operator
    repo: https://seaweedfs.github.io/seaweedfs-operator
    version: 0.1.42
    releaseName: seaweedfs-operator
    namespace: seaweedfs-operator
    includeCRDs: true
    valuesFile: values.yaml
