resources:
  - argocd/application.yaml
  - cert-manager/application.yaml
  - cnpg-barman-cloud-plugin/application.yaml
  - cnpg/application.yaml
  # - opentelemetry-operator/application.yaml
  - startsch/application.yaml
  # - prometheus/application.yaml
  - lgtm/application.yaml
  # - signoz/application.yaml
  - vcluster/application.yaml
