kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: startsch
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/albi005/k8s
    path: startsch
  destination:
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
