resources:
  # TODO: Replace `main` with a git commit hash and set up Renovate to update it automatically
  # https://github.com/renovatebot/renovate/discussions/17318
  - https://raw.githubusercontent.com/kir-dev/StartSCH/refs/heads/main/.config/kubernetes.yaml

patches:
  - target:
      group: postgresql.cnpg.io
      version: v1
      kind: Cluster
      name: startsch-db
      namespace: startsch
    patch: |-
      - op: remove
        path: /spec/storage/storageClass
  - target:
      group: monitoring.coreos.com
      version: v1
      kind: PodMonitor
      name: startsch
      namespace: kube-prometheus-stack
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: monitoring
