kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: my-vcluster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: vcluster
    repoURL: https://charts.loft.sh
    targetRevision: 0.30.4
    helm:
      releaseName: vcluster-1
  destination:
    name: in-cluster
    namespace: vcluster-1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  ignoreDifferences:
  # k8s automatically adds these fields causing a desync. ignore
  - group: apps
    kind: StatefulSet
    jsonPointers:
    - /spec/volumeClaimTemplates/0/apiVersion
    - /spec/volumeClaimTemplates/0/kind
