kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: signoz
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.signoz.io
    targetRevision: 0.105.2
    chart: signoz
  destination:
    name: in-cluster
    namespace: signoz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  ignoreDifferences:
  # k8s automatically adds these fields causing a desync. ignore
  - group: apps
    kind: StatefulSet
    jsonPointers:
    - /spec/volumeClaimTemplates/0/apiVersion
    - /spec/volumeClaimTemplates/0/kind
