# https://github.com/argoproj/argo-helm
# https://artifacthub.io/packages/helm/argo-cd-oci/argo-cd

namespace: argocd

resources:
  - namespace.yaml

helmCharts:
  - name: argo-cd
    repo: oci://ghcr.io/argoproj/argo-helm
    version: 9.3.4
    releaseName: argocd
    apiVersions:
      - monitoring.coreos.com/v1
    # https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd#general-parameters
    # or scroll down to "General parameters" on artifacthub
    # or https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml
    valuesInline:
      configs:
        cm:
          # https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/#kustomizing-helm-charts
          kustomize.buildOptions: "--enable-helm"
      
      # resource requests/limits are from https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml
      controller:
        resources:
          limits:
            cpu: 500m
            memory: 700Mi
          requests:
            cpu: 250m
            memory: 256Mi
      dex:
        initImage:
          resources:
            requests:
              cpu: 5m
              memory: 96Mi
            limits:
              cpu: 10m
              memory: 144Mi
        resources:
          limits:
            cpu: 50m
            memory: 64Mi
          requests:
            cpu: 10m
            memory: 32Mi
      redis:
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
      redisSecretInit:
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
      server:
        extensions:
          resources:
            limits:
              cpu: 50m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
        resources:
          limits:
            cpu: 100m
            memory: 400Mi
          requests:
            cpu: 50m
            memory: 64Mi
      repoServer:
        copyutil:
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 10m
            memory: 64Mi
      applicationSet:
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 300Mi
      notifications:
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
