apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prom-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 80.13.3
    helm:
      valuesObject:
        grafana:
          additionalDataSources:
            - name: Loki
              type: loki
              url: http://loki-gateway.monitoring.svc.cluster.local
            - name: Tempo
              type: tempo
              url: http://tempo.monitoring.svc.cluster.local:3100
        prometheus:
          prometheusSpec:
            # Allow Prometheus to scrape ServiceMonitors in ANY namespace
            serviceMonitorSelectorNilUsesHelmValues: false
            selector: {}
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
