namespace: monitoring
helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 80.13.3
    releaseName: kube-prometheus-stack
    namespace: monitoring
    includeCRDs: true
    valuesInline:
      grafana:
        # set a default password otherwise helm makes things non-reproducible by generating a random password
        adminPassword: "admin"
        
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi

        additionalDataSources:
          - name: Loki
            type: loki
            uid: loki
            access: proxy
            url: http://loki-gateway.monitoring.svc.cluster.local
            jsonData:
              maxLines: 1000
          - name: Tempo
            type: tempo
            uid: tempo
            access: proxy
            url: http://tempo.monitoring.svc.cluster.local:3200
      prometheus:
        prometheusSpec:
          serviceMonitorSelectorNilUsesHelmValues: false
          selector: {}
