kube-prometheus-stack:
  grafana:
    additionalDataSources:
      - name: Loki
        type: loki
        url: http://loki-gateway.monitoring.svc.cluster.local
      - name: Tempo
        type: tempo
        url: http://tempo.monitoring.svc.cluster.local:3200
  prometheus:
    prometheusSpec:
      # Allow Prometheus to scrape ServiceMonitors in ANY namespace
      serviceMonitorSelectorNilUsesHelmValues: false
      selector: {}
