namespace: cnpg-system
resources:
  - namespace.yaml
helmCharts:
  - name: cloudnative-pg
    repo: https://cloudnative-pg.github.io/charts
    version: 0.27.0
    releaseName: cnpg
    namespace: cnpg-system
    includeCRDs: true
