kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: lgtm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: lgtm-distributed
    targetRevision: 2.1.0
    helm:
      parameters:
        - name: installCRDs
          value: "true"
  destination:
    name: in-cluster
    namespace: lgtm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
