kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: lgtm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: lgtm-distributed
    targetRevision: 2.1.0
    helm:
      parameters:
        - name: installCRDs
          value: "true"
  destination:
    name: in-cluster
    namespace: lgtm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
  ignoreDifferences:
  # k8s automatically adds these fields causing a desync. ignore
  - group: apps
    kind: StatefulSet
    jsonPointers:
    - /spec/volumeClaimTemplates/0/apiVersion
    - /spec/volumeClaimTemplates/0/kind
  - group: apps
    kind: Deployment
    name: signoz-clickhouse-operator
    jqPathExpressions:
    - .spec.template.spec.containers[].env[].valueFrom.resourceFieldRef.divisor
