kind: ClusterIssuer
apiVersion: cert-manager.io/v1
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    email: support@sch.bme.hu
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: traefik
            serviceType: ClusterIP
